branches:
  except:
  - experimental
  - legacy
  only:
  - master
deploy:
  on:
    branch: master
  provider: script
  script: resources/deploy.sh
  skip_cleanup: true
git:
  depth: 2
  lfs_skip_smudge: true
language: node_js
node_js: '7'
